# Generated by Django 5.0.6 on 2024-05-18 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_output', models.TextField()),
                ('model_input', models.TextField()),
                ('hf_model_name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('EN', 'English'), ('FI', 'Finnish'), ('FR', 'French'), ('SV', 'Swedish'), ('ZH', 'Chinese')], max_length=2)),
                ('json_meta', models.TextField()),
                ('wikipedia_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('FI', 'Finnish'), ('FR', 'French'), ('SV', 'Swedish'), ('ZH', 'Chinese')], max_length=2)),
                ('annotator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_highlighted_spans', models.TextField()),
                ('is_hallucination', models.BooleanField()),
                ('global_comments', models.TextField()),
                ('highlights_comments', models.TextField()),
                ('datapoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.datapoint')),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.profile')),
            ],
        ),
    ]
