# Generated by Django 5.0.6 on 2024-05-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='global_comments',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='highlights_comments',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='is_hallucination',
        ),
    ]
