# Generated by Django 5.0.6 on 2024-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_rename_global_comments_annotation_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='language',
            field=models.CharField(choices=[('AR', 'Arabic'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FI', 'Finnish'), ('FR', 'French'), ('IT', 'Italian'), ('SV', 'Swedish'), ('ZH', 'Chinese')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('AR', 'Arabic'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FI', 'Finnish'), ('FR', 'French'), ('IT', 'Italian'), ('SV', 'Swedish'), ('ZH', 'Chinese')], max_length=2),
        ),
    ]
